In [1]:
import numpy as np

#1D NumPy Array  integers from 1 to 20
array_1d = np.arange(1, 21)
print("!!*******************!!")
print("1D Array:", array_1d)
print("!!*******************!!")

#Calculate SUM, MEAN, MEDIAN & SD
print("Sum    :", np.sum(array_1d))
print("Mean   :", np.mean(array_1d))
print("Median :", np.median(array_1d))
print("Standard Deviation:", np.std(array_1d))

# indices of elements > 10
indices_gt_10 = np.where(array_1d > 10)
print("!!****************************************!!")
print("Indices of elements > 10:", indices_gt_10[0])
print("!!****************************************!!")

# 2D Array Shape(4X4) Numbers from 1 to 16
array_2d = np.arange(1, 17).reshape(4, 4)
#array_Shape =array_2d.reshape(4, 4)
print("!!****************************************!!")
print("2D Array:\n", array_2d)
print("!!****************************************!!")

#Transpose Array
transpose = array_2d.T
print("!!***************************!!")
print("Transpose:\n", transpose)
print("!!***************************!!")

# Row & Column-wise Sum
print("Row-wise sum:", np.sum(array_2d, axis=1))
print("Column-wise sum:", np.sum(array_2d, axis=0))

# Two 3X3 Array: Random integers from 1 to 20
array_a = np.random.randint(1, 21, (3, 3))
array_b = np.random.randint(1, 21, (3, 3))

print("!!***************************!!")
print("Array A:\n", array_a)
print("!!***************************!!")
print("Array B:\n", array_b)
print("!!***************************!!")

# Element-wise Operations
print("Addition:\n", array_a + array_b)
print("!!***************************!!\n")
print("Subtraction:\n", array_a - array_b)
print("!!***************************!!\n")
print("Multiplication:\n", array_a * array_b)

# Dot Product
dot_product = np.dot(array_a, array_b)
print("!!***************************!!")
print("Dot Product:\n", dot_product)
print("!!***************************!!")

# Reshape 1D Array size 12 into a 3X4 2D Array
array_12 = np.arange(1, 13)
rshaped_array = array_12.reshape(3, 4)
print("Reshaped 3X4 Array:\n", rshaped_array)

#Slice: First 2-Rows & Last 2-Cols
Sliced = reshaped_array[:2, -2:]
print("!!****************************************!!")
print("Sliced:First 2-Rows & Last 2-Cols:\n", Sliced)
print("!!****************************************!!")

!!*******************!!
1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
!!*******************!!
Sum    : 210
Mean   : 10.5
Median : 10.5
Standard Deviation: 5.766281297335398
!!****************************************!!
Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]
!!****************************************!!
!!****************************************!!
2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
!!****************************************!!
!!***************************!!
	Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
!!***************************!!
Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]
!!***************************!!
Array A:
 [[ 1  9 19]
 [15  1 10]
 [ 6  1  6]]
!!***************************!!
Array B:
 [[13 12 19]
 [18 20  6]
 [20  4 12]]
!!***************************!!
Addition:
 [[14 21 38]
 [33 21 16]
 [26  5 18]]
!!***************************!!

Subtraction:
 [[-12  -3

NameError: name 'reshaped_array' is not defined