In [1]:
# Importing NumPy
import numpy as np

# --------------------------------------------
# 1. 1D NumPy Array from 1 to 20
# --------------------------------------------

arr_1d = np.arange(1, 21)

# a. Sum, Mean, Median, Std Deviation
sum_arr = np.sum(arr_1d)
mean_arr = np.mean(arr_1d)
median_arr = np.median(arr_1d)
std_arr = np.std(arr_1d)

print("1D Array:", arr_1d)
print("Sum:", sum_arr)
print("Mean:", mean_arr)
print("Median:", median_arr)
print("Standard Deviation:", std_arr)

# b. Indices of elements greater than 10
indices_gt_10 = np.where(arr_1d > 10)[0]
print("Indices of elements > 10:", indices_gt_10)

# --------------------------------------------
# 2. 2D NumPy Array (4x4) with values from 1 to 16
# --------------------------------------------

arr_2d = np.arange(1, 17).reshape(4, 4)

# a. Print the array
print("\n2D Array (4x4):\n", arr_2d)

# b. Transpose of the array
transpose_arr = arr_2d.T
print("Transpose:\n", transpose_arr)

# c. Row-wise and Column-wise sums
row_sum = np.sum(arr_2d, axis=1)
col_sum = np.sum(arr_2d, axis=0)

print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)

# --------------------------------------------
# 3. Two 3x3 Random Arrays
# --------------------------------------------

np.random.seed(0)  # For reproducibility

a = np.random.randint(1, 21, size=(3, 3))
b = np.random.randint(1, 21, size=(3, 3))

print("\nArray A:\n", a)
print("Array B:\n", b)

# a. Element-wise operations
add_ab = a + b
sub_ab = a - b
mul_ab = a * b

print("Element-wise Addition:\n", add_ab)
print("Element-wise Subtraction:\n", sub_ab)
print("Element-wise Multiplication:\n", mul_ab)

# b. Dot product
dot_product = np.dot(a, b)
print("Dot Product:\n", dot_product)

# --------------------------------------------
# 4. Reshape and Slice
# --------------------------------------------

arr_reshape = np.arange(1, 13).reshape(3, 4)

print("\nReshaped Array (3x4):\n", arr_reshape)

# Slice: First two rows and last two columns
sliced = arr_reshape[:2, -2:]
print("Sliced (First 2 rows, Last 2 columns):\n", sliced)

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]

2D Array (4x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]

Array A:
 [[13 16  1]
 [ 4  4  8]
 [10 20 19]]
Array B:
 [[ 5  7 13]
 [ 2  7  8]
 [15 18  6]]
Element-wise Addition:
 [[18 23 14]
 [ 6 11 16]
 [25 38 25]]
Element-wise Subtraction:
 [[  8   9 -12]
 [  2  -3   0]
 [ -5   2  13]]
Element-wise Multiplication:
 [[ 65 112  13]
 [  8  28  64]
 [150 360 114]]
Dot Product:
 [[112 221 303]
 [148 200 132]
 [375 552 404]]

Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced (First 2 rows, Last 2 columns):
 [[3 4]
 [7 8]]
